#!/bin/sh
clear

echo ""
echo "= ПОДБИРАЕМ MTU ДЛЯ AMNEZIA-ИНТЕРФЕЙСОВ"

for _iface_name in $(uci show network | grep -oE "network\.[^.]*\.proto='amneziawg'" | cut -d. -f2); do
    ip_addr=$(ip -4 addr show $_iface_name 2>/dev/null | grep -oE 'inet [0-9.]+' | awk '{print $2}')
    [ -z "$ip_addr" ] && continue
	
	# nohostroute проверка
    current_nhr=$(uci get network.$_iface_name.nohostroute 2>/dev/null)
    if [ "$current_nhr" != "1" ]; then
        uci set network.$_iface_name.nohostroute=1
        echo "  $_iface_name nohostroute: $current_nhr -> 1"
        need_reload=1
    fi
    
    
	current_mtu=$(cat /sys/class/net/$_iface_name/mtu 2>/dev/null)
    ip link set dev $_iface_name mtu 1420 2>/dev/null
    
    for size in 1392 1382 1372 1350 1320 1300 1280 1252 1220 1200 1150; do
        mtu=$((size + 28))
        if ping -c1 -W2 -s $size -I $_iface_name 1.1.1.1 >/dev/null 2>&1; then
            if [ "$mtu" != "$current_mtu" ]; then
                uci set network.$_iface_name.mtu="$mtu"
                ip link set dev $_iface_name mtu $mtu 2>/dev/null
                echo "  $_iface_name $current_mtu -> $mtu"
                need_reload=1
            else
                echo "  $_iface_name $current_mtu (ok)"
            fi
            break
        fi
    done
    
    if [ -z "$(uci get network.$_iface_name.mtu 2>/dev/null)" ]; then
        uci set network.$_iface_name.mtu="1280"
        ip link set dev $_iface_name mtu 1280 2>/dev/null
        echo "$_iface_name $current_mtu -> 1280 (fallback)"
        need_reload=1
    fi
done

uci commit network

if [ "$need_reload" = "1" ]; then
    for _iface_name in $(uci show network | grep -oE "network\.[^.]*\.proto='amneziawg'" | cut -d. -f2); do
        ifdown $_iface_name 2>/dev/null
        ifup $_iface_name 2>/dev/null
    done
fi
echo ""
